name: Release Extension

on:
  push:
    tags:
      - 'v*'  # Triggers on any tag starting with 'v' (e.g., v1.0.0, v1.2.3)

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Compile TypeScript
      run: npm run compile
      
    - name: Package extension
      run: npx vsce package
      
    - name: List files
      run: ls -la *.vsix
      
    - name: Create Release
      run: |
        VSIX_FILE=$(ls *.vsix | head -1)
        
        # Generate release notes from commits since last tag
        RELEASE_NOTES=$(gh api repos/${{ github.repository }}/releases --jq '.[0].tag_name' 2>/dev/null || echo "")
        if [ -n "$RELEASE_NOTES" ]; then
          COMMITS=$(git log --pretty=format:"- %s" $RELEASE_NOTES..HEAD)
        else
          COMMITS=$(git log --pretty=format:"- %s" --max-count=10)
        fi
        
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "## What's Changed
        
        $COMMITS
        
        ## Installation
        
        Download the \`.vsix\` file from the assets below and install it in VS Code:
        1. Open VS Code
        2. Go to Extensions (Ctrl+Shift+X)
        3. Click the \"...\" menu and select \"Install from VSIX...\"
        4. Select the downloaded \`.vsix\` file
        
        ## Files
        
        - \`$VSIX_FILE\` - The packaged extension" \
          "$VSIX_FILE"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
